Repository giyasht/Algorithms, pull requests merged in 2022-10, with the labels that each got.

#77 added boyre -moore voting algo and managed files and folders
  Algorithms/Heapsort.cpp
  Algorithms/a.out
  Algorithms/boyre-moore-voting-algorithm.cpp
  Algorithms/bubble_sort_InsaneJ0ker.c
  Algorithms/eight queens problems.cpp
  dfs.c
Labels: hacktoberfest-accepted

#76 Create BellmanFord.cpp
  BellmanFord.cpp
Labels: hacktoberfest-accepted

#78 added bogo sort
  Algorithms/a.out
  Algorithms/bogo-sort.cpp
Labels: hacktoberfest-accepted

#79 Create Activity_Selection.cpp
  Algorithms/Activity_Selection.cpp
Labels: hacktoberfest-accepted

#80 added word search program in c++
  Algorithms/79.word-search.cpp
Labels: hacktoberfest-accepted

#82 Add fizzbuzz in cpp
  CPP_Basics/fizzbuzz.cpp
Labels: hacktoberfest-accepted

#83 Added Sieve of Eratosthenes algorithm
  Algorithms/Sieve_of_Eratosthenes.cpp
Labels: hacktoberfest-accepted

#86 Create rod_cutting.cpp
  Dynamic-Programming-Package/rod_cutting.cpp
Labels: hacktoberfest-accepted

#85 Create sum_triangle.cpp
  CPP_Basics/sum_triangle.cpp
Labels: hacktoberfest-accepted

#87 algorithm to detect cycle in a linked list
  Algorithms/142.linked-list-cycle-ii.cpp
Labels: hacktoberfest-accepted

#88 40. combination-sum2
  CPP_Basics/40.combination-sum2.cpp
Labels: hacktoberfest-accepted

#89 binary tree to doubly linked list in c++ code
  Algorithms/binary-tree-to-doubly-linked-list.cpp
Labels: hacktoberfest-accepted

#90 myCircularQueue.cpp
  Algorithms/myCircularQueue.cpp
Labels: hacktoberfest-accepted

#91 Karatsuba algorithm
  Algorithms/Karatsuba algorithm.cpp
Labels: hacktoberfest-accepted

#92 Added Banker's Algorithm
  BANKERS-ALGO.cpp
Labels: hacktoberfest-accepted

#93 Added Sieve of Eratosthenes code in Java
  CPP_Basics/Sieve of Eratosthenes.java
Labels: hacktoberfest-accepted

#94 Create QueueStacks.c
  QueueStacks.c
Labels: hacktoberfest-accepted, hacktoberfest

#95 adding a Reverse_Node_in_k-group.cpp file
  Algorithms/Reverse_Node_in_k-group.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#96 Sanketr113
  Algorithms/CircularDoubleLinkedList.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#97 Create BinaryTree.c
  BinaryTree.c
Labels: hacktoberfest-accepted, hacktoberfest

#98 Create SparseMat.cpp
  SparseMat.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#99 Kartik Patel : Optimized Bubble sort Java
  Algorithms/BubbleSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#101 Create doubly_linked_list.cpp
  doubly_linked_list.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#102 Create SwapNodesInPairs.c
  SwapNodesInPairs.c
Labels: hacktoberfest-accepted, hacktoberfest

#103 Create deleteDuplicates.c
  Algorithms/deleteDuplicates.c
Labels: hacktoberfest-accepted, hacktoberfest

#104 Brian Kernighan’s algorithm
  Algorithms/Brian_Kernighan’s_algorithm.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#105 added Heap data structure
  Heap.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#107 Create Peak Index of an Mountain Array.cpp
  Peak Index of an Mountain Array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#109 57.LFU Cache.cpp
  57.LFU Cache.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#110 reverse a linked list
  Algorithms_Reverse_a_linked_list.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#112 Added 16. 3Sum Closest problem leetcode in JAVA
  16. 3Sum Closest.java
Labels: hacktoberfest-accepted, hacktoberfest

#113 Created number-of-weak-characters-in-the-game.java
  number-of-weak-characters-in-the-game.java
Labels: hacktoberfest-accepted, hacktoberfest

#114 substrings of length k with k-1 distinct elements
  Substrings of length k with k-1 distinct elements.java
Labels: hacktoberfest-accepted, hacktoberfest

#115 Add Singly LinkedList
  DataStructuresUsingClasses/singly_linked_list.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#116 leetcode question to merge BST
  Algorithms/mergeBST.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#117 Kth Smallest Element problem
  .vscode/settings.json
  kthSmallestElement.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#118 Solve alien dictionary
  Alien_dictionary.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#119 Add Binary Tree zigzag traversal
  Algorithms/103-binary-tree-zigzag-level-order-traversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#120 111.minimum-depth-of-binary-tree.cpp
  111.minimum-depth-of-binary-tree.cpp
  234.palindrome-linked-list.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#121 958.check-completeness-of-a-binary-tree.cpp
  958.check-completeness-of-a-binary-tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#122 215.kth-largest-element-in-an-array.cpp
  215.kth-largest-element-in-an-array.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#123 236.lowest-common-ancestor-of-a-binary-tree.cpp
  236.lowest-common-ancestor-of-a-binary-tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#124 added z-algorithm in JS
  Algorithms/Z algorithm.js
Labels: hacktoberfest-accepted, hacktoberfest

#125 XOR Encryption by Shifting Plaintext
  XOR Encryption by Shifting Plaintext.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#126 Create cutting_a_rod.cpp
  cutting_a_rod.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#127 Create LCS_dp.cpp
  LCS_dp.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#128 Create CyclicSort.java
  Algorithms/CyclicSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#129 Merge Longest Alternating Subsequence in Dynamic Programming
  Dynamic-Programming-Package/Longest_Alternating_Subsequence.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#130 Create fibo.py
  fibo.py
Labels: hacktoberfest-accepted, hacktoberfest

#131 QUICK SORT
  Algorithms/QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#132 BinarySearch
  Algorithms/BinarySearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#133 Create Sudoku_Solver.cpp
  Algorithms/Sudoku_Solver.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#137 Added Dijkstra's Algorithm in C++
  Algorithms/Dijkstra's Algorithm.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#138 Create assign-cookies.cpp
  Algorithms/assign-cookies.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#140 DES algorithm in C++
  Algorithms/data_encryption_standard.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#141 Two Sum
  Two Sum
Labels: hacktoberfest-accepted, hacktoberfest

#142 Added treasure Hunt
  Algorithms/treasure_hunt.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#143 added combination sum leetcode problem 39
  combinationSum.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#144 added prim's algorithm
  prims's_algo.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#145 Create treetraversal.cpp
  treetraversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#146 Create simple_sieve.cpp
  simple_sieve.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#147 Hacktoberfest-2022
  If-else statment.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#149 Added largest rectangle in histogram
  Largest_Rectangle_in_Histogram.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#150 Segmented Sieve in cpp
  Algorithms/Sieve_of_Eratosthenes.cpp
  Algorithms/segmentedSeive.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#151 Create gold_min_problem.cpp
  gold_min_problem.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#152 Create subset_sum_problem.cpp
  subset_sum_problem.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#154 Create Palindrome Partition Solution
  Palindrome_Partition.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#153 Leetcode problems solution in JAVA
  11. Container With Most Water
  1812. Determine Color of a Chessboard Square
Labels: hacktoberfest-accepted, hacktoberfest

#155 CF-1736D Equal Binary Subsequences
  Equal_Binary_Subsequences.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#158 To find leap year
  leapyear.c
Labels: hacktoberfest-accepted, hacktoberfest

#157 CodeForces - Divisibility by 2^n
  Divisibility_by_2^n.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#159 radix_sort_algorithm
  radixsort.c
Labels: hacktoberfest-accepted, hacktoberfest

#160 hacktoberfest2022
  sortbubble.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#161 Create Two Knights Solution
  Two_Knights.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#163 CABFINDER
  cabFinder.cpc.txt
Labels: hacktoberfest-accepted, hacktoberfest

#162 Palindrome number checker
  ascii.cpp
  palindrome.cpc.txt
Labels: hacktoberfest-accepted, hacktoberfest
